version: '3.8'

services:
  db:
    image: postgres:15
    container_name: webhook_db
    environment:
      POSTGRES_DB: webhook_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/webhook_db

volumes:
  postgres_data:
